# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b9ac9977b48fcb0cf94b6b9d5aa0d9bb7fc2cfa6a634449de293c5ad63c1c0a641c9df26d33cd75a18c77e18481cc76e1984c204fc4ae8c43aaeed90111229

test:
  secret_key_base: d5be4a95e93a50032091760ba9f3d30adff5f42469f8455c7e84d3fc287a5488eaddb2569f1d1a8db87f0e5b012150b700964d65ebc2d93a14a569f76e36614a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
